import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowRight, BadgeCheck, ChevronRight, Clock3, MapPin, Plus, Search, ShieldCheck, Star, Wrench } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

const jobs = [
  { title: 'Burst pipe repair', category: 'Plumbing', status: 'Receiving quotes', location: 'Centurion', bids: 3, urgency: 'Urgent', date: 'Today', color: 'bg-destructive/10 text-destructive' },
  { title: 'Exterior wall painting', category: 'Painting', status: 'Provider confirmed', location: 'Midrand', bids: 1, urgency: 'This week', date: '24 Aug', color: 'bg-emerald-100 text-emerald-700' },
]

const quotes = [
  { name: "Mike's Plumbing", initials: 'MP', rating: '4.9', reviews: '127 jobs', price: 'R750', arrival: '35 min', availability: 'Available now', emergency: true, tag: 'Best match' },
  { name: 'Emergency Plumbing SA', initials: 'ES', rating: '4.8', reviews: '89 jobs', price: 'R900', arrival: '18 min', availability: 'Available now', emergency: true, tag: 'Fastest' },
]

export const Route = createFileRoute('/app/')({
  head: () => ({ meta: [{ title: 'Dashboard · FixNow' }, { name: 'description', content: 'Manage your FixNow jobs and compare trusted professionals.' }] }),
  component: DashboardHome,
})

function DashboardHome() {
  return <div className="mx-auto max-w-7xl space-y-8 p-5 sm:p-8">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-accent-foreground">Monday, 17 August 2026</p><h1 className="mt-2 font-serif text-4xl tracking-[-.05em] text-primary sm:text-5xl">Good evening, Thandi.</h1><p className="mt-2 text-sm text-muted-foreground">Here’s what’s happening with your service jobs.</p></div><Button asChild className="w-fit rounded-full bg-accent text-accent-foreground hover:bg-accent/90"><Link to="/"><Plus className="size-4" /> Post a new job</Link></Button></div>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Active jobs" value="2" icon={<Wrench className="size-4" />} /><Stat label="Pending quotes" value="3" icon={<Search className="size-4" />} /><Stat label="Completed jobs" value="8" icon={<BadgeCheck className="size-4" />} /></div>
    <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
      <section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-primary">Your active jobs</h2><p className="mt-1 text-sm text-muted-foreground">Keep an eye on every job from post to done.</p></div><button className="text-sm font-semibold text-accent-foreground hover:underline">View all</button></div>{jobs.map((job) => <Card key={job.title} className="overflow-hidden border-border/80 shadow-sm transition-shadow hover:shadow-md"><CardContent className="p-0"><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Wrench className="size-5" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-primary">{job.title}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${job.color}`}>{job.urgency}</span></div><p className="mt-1 text-xs text-muted-foreground">{job.category} · {job.status}</p><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><MapPin className="size-3.5" /> {job.location}</span><span className="flex items-center gap-1"><Clock3 className="size-3.5" /> {job.date}</span><span className="font-semibold text-accent-foreground">{job.bids} quote{job.bids === 1 ? '' : 's'}</span></div></div></div><Button variant="outline" size="sm" className="w-full rounded-full sm:w-auto">View job <ChevronRight className="size-4" /></Button></div>{job.bids > 1 && <div className="flex items-center justify-between border-t border-border bg-accent/10 px-5 py-3 text-xs"><span className="flex items-center gap-2 font-semibold text-primary"><BellDot /> New quotes are ready to compare</span><span className="font-bold text-accent-foreground">Review now <ArrowRight className="ml-1 inline size-3" /></span></div>}</CardContent></Card>)}</section>
      <section><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-primary">Compare quotes</h2><p className="mt-1 text-sm text-muted-foreground">Burst pipe repair</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">3 total</span></div><Card className="mt-4 border-accent/30 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-sm text-primary"><ShieldCheck className="size-4 text-emerald-700" /> Every quote is transparent</CardTitle></CardHeader><CardContent className="space-y-3">{quotes.map((quote) => <div key={quote.name} className="rounded-xl border border-border bg-background p-3"><div className="flex items-start gap-2.5"><span className="flex size-9 items-center justify-center rounded-full bg-primary text-[10px] font-bold text-primary-foreground">{quote.initials}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="truncate text-xs font-bold text-primary">{quote.name}</span><span className="rounded-full bg-accent/15 px-2 py-0.5 text-[9px] font-bold text-accent-foreground">{quote.tag}</span></div><div className="mt-1 flex items-center gap-2 text-[10px] text-muted-foreground"><span className="flex items-center gap-0.5 text-accent-foreground"><Star className="size-3 fill-current" /> {quote.rating}</span><span>· {quote.reviews}</span></div><div className="mt-1.5 flex items-center gap-1 text-[10px] font-semibold text-emerald-700"><span className="size-1.5 rounded-full bg-emerald-600" /> {quote.availability}{quote.emergency && <span className="ml-1 rounded-full bg-destructive/10 px-1.5 py-0.5 text-destructive">Emergency jobs</span>}</div></div></div><div className="mt-3 flex items-end justify-between"><div><div className="text-lg font-bold text-primary">{quote.price}</div><div className="text-[10px] text-muted-foreground">arrives in {quote.arrival}</div></div><Button size="sm" className="h-8 rounded-full bg-primary text-xs">View profile</Button></div></div>)}<button className="w-full pt-1 text-center text-xs font-semibold text-accent-foreground hover:underline">See all quote details <ArrowRight className="ml-1 inline size-3" /></button></CardContent></Card></section>
    </div>
    <Card className="border-primary/10 bg-primary text-primary-foreground shadow-lg"><CardContent className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><div className="flex items-center gap-2 text-sm font-bold text-accent"><ShieldCheck className="size-5" /> Your FixNow protection</div><p className="mt-2 max-w-xl text-sm leading-6 text-primary-foreground/75">Your exact address stays private until you hire. Payments are secured until you confirm the job is done.</p></div><Button variant="outline" className="w-fit rounded-full border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-primary">Learn how it works <ArrowRight className="size-4" /></Button></CardContent></Card>
  </div>
}

function Stat({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <Card className="border-border/80 shadow-sm"><CardContent className="flex items-center gap-3 p-4"><span className="flex size-9 items-center justify-center rounded-xl bg-accent/15 text-accent-foreground">{icon}</span><div><div className="text-2xl font-bold text-primary">{value}</div><div className="text-xs text-muted-foreground">{label}</div></div></CardContent></Card> }
function BellDot() { return <span className="relative flex size-4"><span className="absolute right-0 top-0 size-1.5 rounded-full bg-accent" /><BellIcon /></span> }
function BellIcon() { return <span className="mt-1 block size-2.5 rounded-full border-2 border-accent-foreground" /> }
